#!/bin/sh

# Copyright (c) 2019 Purism SPC
# Changes (c) 2021 by Samuel Mueller

PUBKEY=$1
MY_DEVICE=$2
TMPDIR=`mktemp --tmpdir=/dev/shm --directory`
TMPKEY="${TMPDIR}/tmpkey"
GNUPGHOME="${TMPDIR}"
CRYPTHOME="/etc/cryptsetup-initramfs"
ROOT_DEV=""
ROOT_DEV_FULL=""
GNUPGSC_HOOK="/usr/share/initramfs-tools/hooks/cryptgnupg-sc"
GNUPGSC_OSK_HOOK="${GNUPGSC_HOOK}-osk"
GNUPGSC_SCRIPT="/lib/cryptsetup/scripts/decrypt_gnupg-sc"
GNUPGSC_OSK_SCRIPT="${GNUPGSC_SCRIPT}-osk"

. /lib/cryptsetup/functions

if [ ! -e "$PUBKEY" ]; then
  echo "ERROR: This script requires a GPG public key to encrypt your LUKS secret against"
  echo "Usage: $0 <gpg_public_key.asc>"
  exit 1
fi

# Discover the root LUKS device
ROOT_LUKS=`grep -v '^#' /etc/fstab | col | egrep '[[:space:]]+\/[[:space:]]+' | cut -f1 -d ' '| sed 's/\/dev\/mapper\///'`
case $ROOT_LUKS in
UUID=*)
  UUID=`echo $ROOT_LUKS | cut -f2 -d '='`
  ROOT_LUKS=`blkid -U $UUID | sed 's/\/dev\/mapper\///'`
  ;;
esac
crypttab_find_entry $ROOT_LUKS
ROOT_DEV=$CRYPTTAB_SOURCE

case $ROOT_DEV in
UUID=*)
  UUID=`echo $ROOT_DEV | cut -f2 -d '='`
  ROOT_DEV_FULL="/dev/disk/by-uuid/$UUID"
  ;;
LABEL=*)
  LABEL=`echo $ROOT_DEV | cut -f2 -d '='`
  ROOT_DEV_FULL="/dev/disk/by-label/$LABEL"
  ;;
PARTLABEL=*)
  PARTLABEL=`echo $ROOT_DEV | cut -f2 -d '='`
  ROOT_DEV_FULL="/dev/disk/by-partlabel/$PARTLABEL"
  ;;
PARTUUID=*)
  PARTUUID=`echo $ROOT_DEV | cut -f2 -d '='`
  ROOT_DEV_FULL="/dev/disk/by-uuid/$PARTUUID"
  ;;
*)
  ROOT_DEV_FULL=$ROOT_DEV
  ;;
esac

if [ ! -e "$ROOT_DEV_FULL" ]; then
  echo No valid root device found! Aborting!
  exit 1
fi

if dpkg-query -l 'scdaemon' | egrep -q '^ii'; then
  echo "scdaemon installed"
else
  echo "ERROR: scdaemon package not installed. The scdaemon package is required to access the OpenPGP smart card"
  echo "Trying to install it now..."
  if apt update && apt install -y scdaemon
  then
      echo "Installed scdaemon successfully"
  else
      echo "Couldn't install scdaemon"
      exit 1
  fi
fi
  
chmod 700 $GNUPGHOME
# create cryptfs GPG home dir
gpg --homedir ${GNUPGHOME} --card-status
if [ $? -ne 0 ]; then
  echo Insert your OpenPGP smart card and press Enter
  read _
  gpg --homedir ${GNUPGHOME} --card-status || exit 1
fi

gpg --homedir ${GNUPGHOME} --import $PUBKEY
gpg --homedir ${GNUPGHOME} --export --export-options export-minimal > ${CRYPTHOME}/pubring.gpg
GPG_RECIPIENT=`gpg --homedir="$GNUPGHOME" --with-colons --list-keys \
    | sed -nr 's/^pub(:[^:]*){3}:([0-9a-fA-F]+)(:[^:]*){6}:[^:]*[eE].*/-r \2/p'`

if [ "$GPG_RECIPIENT" = "" ]; then
  echo "ERROR: No GPG keys found in keyring"
  exit 1
fi

# Generate the LUKS key if it doesn't exist
if [ -e "${CRYPTHOME}/cryptkey.gpg" ]; then
  echo "${CRYPTHOME}/cryptkey.gpg exists, skipping key generation"
else
# generate secret key
  dd if=/dev/random bs=1 count=256 >${TMPKEY}
  gpg --homedir ${GNUPGHOME} --trust-model=always -o ${CRYPTHOME}/cryptkey.gpg $GPG_RECIPIENT --yes --encrypt ${TMPKEY}
  if [ $? -ne 0 ]; then
    echo "Encryption of ${CRYPTHOME}/cryptkey.gpg failed! Aborting!"
    shred -u ${TMPKEY}
    shred -u ${CRYPTHOME}/cryptkey.gpg
    exit 1
  fi
  
  # test decryption
  GNUPGHOME=$GNUPGHOME /lib/cryptsetup/scripts/decrypt_gnupg-sc ${CRYPTHOME}/cryptkey.gpg > /dev/null
  
  if [ $? -ne 0 ]; then
    echo "Decryption test for ${CRYPTHOME}/cryptkey.gpg failed! Aborting!"
    shred -u ${TMPKEY}
    shred -u ${CRYPTHOME}/cryptkey.gpg
    exit 1
  fi
  
  echo -e "\n\nAdding your new secret key to LUKS.\nWhen prompted, type in your OLD passphrase to unlock the disk."
  cryptsetup luksAddKey $ROOT_DEV_FULL ${TMPKEY}
  if [ $? -ne 0 ]; then
    echo "Adding new key to LUKS failed! Aborting!"
    shred -u ${TMPKEY}
    shred -u ${CRYPTHOME}/cryptkey.gpg
    exit 1
  fi
  shred -u ${TMPKEY}
fi

#Add initramfs hook
cp "${GNUPGSC_HOOK}" "${GNUPGSC_OSK_HOOK}"
if sed -i "s/decrypt_gnupg-sc/decrypt_gnupg-sc-osk/g" "${GNUPGSC_OSK_HOOK}"
then
  echo "Created ${GNUPGSC_OSK_HOOK} successfully"
else
  echo "Problems creating ${GNUPGSC_OSK_HOOK}"
  exit 2
fi

#Adding new cryptsetup script
if cp files/decrypt_gnupg-sc-osk "${GNUPGSC_OSK_SCRIPT}" && chmod 755 "${GNUPGSC_OSK_SCRIPT}"
then
  echo "Created ${GNUPGSC_OSK_SCRIPT} successfully"
else
  echo "Problems creating ${GNUPGSC_OSK_SCRIPT}"
  exit 2
fi

#Load Pinephone USB-C Kernel module in initramfs
if ! grep "^anx7688" /etc/initramfs-tools/modules >/dev/null
then
  if [ "${MY_DEVICE}" = "pinephone" ] || [ "${MY_DEVICE}" = "Pinephone" ] || [ "${MY_DEVICE}" = "PinePhone" ] || [ "${MY_DEVICE}" = "PP" ] || [ "${MY_DEVICE}" = "pp" ]
  then
      echo "anx7688" >> /etc/initramfs-tools/modules
      echo "Added anx7688 to /etc/initramfs-tools/modules to support USB-C in the initramfs on the PinePhone"
  else
      echo "Pinephone parameter not given, not adding kernel module anx7688 (for the USB-C controller of the PinePhone) to /etc/initramfs-tools/modules"
      echo "Make sure the module is loaded in the initramfs kernel if you want to use the USB-C port to connect a smart-card"
  fi
fi

# Configure Librem 5 internal smart card reader if present
if [ -f /sys/class/leds/smc_en_brightness ]; then
  if [ "${MY_DEVICE}" = "librem5" ] || [ "${MY_DEVICE}" = "Librem5" ] || [ "${MY_DEVICE}" = "Librem 5" ] || [ "${MY_DEVICE}" = "librem 5" ] || [ "${MY_DEVICE}" = "l5" ]
  then
		cp "files/cryptgnupg-sc-osk-hook" "${GNUPGSC_OSK_HOOK}" && chmod 755 "${GNUPGSC_OSK_HOOK}"
		cp "files/cryptgnupg-sc-osk-script" "/usr/share/initramfs-tools/scripts/local-top/cryptgnupg-sc-osk" && chmod 755 "/usr/share/initramfs-tools/scripts/local-top/cryptgnupg-sc-osk"
    echo "Configured internal Librem 5 smart card reader"
  else
		echo "Librem5 parameter not given, not configuring internal smart card reader"
  fi
fi

crypttab_find_entry $ROOT_LUKS
if [ "${CRYPTHOME}/cryptkey.gpg" = "$CRYPTTAB_KEY" ]; then
  echo "/etc/crypttab already updated, skipping"
else
  CRYPTTAB_OPTIONS="${CRYPTTAB_OPTIONS%',keyscript='*}"
  cat /etc/crypttab | sed "s|^$ROOT_LUKS .*|$ROOT_LUKS $ROOT_DEV ${CRYPTHOME}/cryptkey.gpg ${CRYPTTAB_OPTIONS},keyscript=decrypt_gnupg-sc-osk|" > /etc/crypttab.tmp
  mv /etc/crypttab.tmp /etc/crypttab
fi

update-initramfs -u
